examplesite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^shout/', include('shoutbox.urls')),
    url(r'^admin/', admin.site.urls),
]

shoutbox/urls.py
from django.conf.urls import url

from . import views

app_name = 'shoutbox'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^shout/$', views.shout, name='shout'),
    url(r'^ip/$', views.ip, name='ip')
]

shoutbox/models.py
from __future__ import unicode_literals

from django.db import models

class Shout(models.Model):
    message = models.CharField(max_length=200)
    sender = models.CharField(max_length=50)
    date = models.DateTimeField(auto_now=True)

shoutbox/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

from requests import get

from .models import Shout


def index(request):
    context = {'shouts': Shout.objects.all()}
    return render(request, 'shoutbox/index.html', context)


def shout(request):
    sender = request.POST['sender']
    message = request.POST['message']
    Shout.objects.create(sender=sender, message=message)
    return HttpResponseRedirect(reverse('shoutbox:index'))


def ip(request):
    return HttpResponse(get('https://httpbin.org/ip'))

shoutbox/templates/shoutbox/index.html
{% load staticfiles %}
<img src="{% static "shoutbox/kamaji.png" %}" />
{% for shout in shouts %}
    <li>{{ shout.sender }} shouted: {{ shout.message }} @ {{ shout.date }} </li>
{% endfor %}

<form action="{% url 'shoutbox:shout' %}" method="post">
    {% csrf_token %}

    <input type="text" name="sender" />
    <input type="text" name="message" />
    <input type="submit" value="Shout!" />
</form>